#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
/* 
 * Cách tạo DataContext và kết nối cơ sở dữ liệu Microsoft SQL Server: https://www.youtube.com/watch?v=xwzzGhx3Sxg
 */
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Db_ProductManagement")]
	public partial class Db_ProductManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDanhMuc(DanhMuc instance);
    partial void UpdateDanhMuc(DanhMuc instance);
    partial void DeleteDanhMuc(DanhMuc instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    #endregion
		
		public Db_ProductManagementDataContext() : 
				base(global::DataAccessLayer.Properties.Settings.Default.Db_ProductManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Db_ProductManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_ProductManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_ProductManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_ProductManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DanhMuc> DanhMucs
		{
			get
			{
				return this.GetTable<DanhMuc>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertSanPham")]
		public int InsertSanPham([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mainsertproc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string nameinsertproc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> giainsertproc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> madminsertproc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mainsertproc, nameinsertproc, giainsertproc, madminsertproc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdatePriceSanPham")]
		public int UpdatePriceSanPham([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maspupdateproc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string tenspupdateproc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dongiaupdateproc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> madmupdateproc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maspupdateproc, tenspupdateproc, dongiaupdateproc, madmupdateproc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryAllSanPham")]
		public ISingleResult<QueryAllSanPhamResult> QueryAllSanPham()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<QueryAllSanPhamResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryDanhMuc")]
		public ISingleResult<QueryDanhMucResult> QueryDanhMuc()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<QueryDanhMucResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryDanhMucTheoMaDm")]
		public ISingleResult<QueryDanhMucTheoMaDmResult> QueryDanhMucTheoMaDm([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ma)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma);
			return ((ISingleResult<QueryDanhMucTheoMaDmResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QuerySanPhamTheoMaDm")]
		public ISingleResult<QuerySanPhamTheoMaDmResult> QuerySanPhamTheoMaDm([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maqueryproc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maqueryproc);
			return ((ISingleResult<QuerySanPhamTheoMaDmResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QuerySanPhamTheoMaSp")]
		public ISingleResult<QuerySanPhamTheoMaSpResult> QuerySanPhamTheoMaSp([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maspqueryproc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maspqueryproc);
			return ((ISingleResult<QuerySanPhamTheoMaSpResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMuc")]
	public partial class DanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDm;
		
		private string _TenDm;
		
		private EntitySet<SanPham> _SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDmChanging(int value);
    partial void OnMaDmChanged();
    partial void OnTenDmChanging(string value);
    partial void OnTenDmChanged();
    #endregion
		
		public DanhMuc()
		{
			this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDm", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDm
		{
			get
			{
				return this._MaDm;
			}
			set
			{
				if ((this._MaDm != value))
				{
					this.OnMaDmChanging(value);
					this.SendPropertyChanging();
					this._MaDm = value;
					this.SendPropertyChanged("MaDm");
					this.OnMaDmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDm", DbType="NVarChar(250)")]
		public string TenDm
		{
			get
			{
				return this._TenDm;
			}
			set
			{
				if ((this._TenDm != value))
				{
					this.OnTenDmChanging(value);
					this.SendPropertyChanging();
					this._TenDm = value;
					this.SendPropertyChanged("TenDm");
					this.OnTenDmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMuc_SanPham", Storage="_SanPhams", ThisKey="MaDm", OtherKey="MaDm")]
		public EntitySet<SanPham> SanPhams
		{
			get
			{
				return this._SanPhams;
			}
			set
			{
				this._SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.DanhMuc = this;
		}
		
		private void detach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.DanhMuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSp;
		
		private string _TenSp;
		
		private System.Nullable<int> _DonGia;
		
		private System.Nullable<int> _MaDm;
		
		private EntityRef<DanhMuc> _DanhMuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSpChanging(int value);
    partial void OnMaSpChanged();
    partial void OnTenSpChanging(string value);
    partial void OnTenSpChanged();
    partial void OnDonGiaChanging(System.Nullable<int> value);
    partial void OnDonGiaChanged();
    partial void OnMaDmChanging(System.Nullable<int> value);
    partial void OnMaDmChanged();
    #endregion
		
		public SanPham()
		{
			this._DanhMuc = default(EntityRef<DanhMuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSp", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSp
		{
			get
			{
				return this._MaSp;
			}
			set
			{
				if ((this._MaSp != value))
				{
					this.OnMaSpChanging(value);
					this.SendPropertyChanging();
					this._MaSp = value;
					this.SendPropertyChanged("MaSp");
					this.OnMaSpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSp", DbType="NVarChar(250)")]
		public string TenSp
		{
			get
			{
				return this._TenSp;
			}
			set
			{
				if ((this._TenSp != value))
				{
					this.OnTenSpChanging(value);
					this.SendPropertyChanging();
					this._TenSp = value;
					this.SendPropertyChanged("TenSp");
					this.OnTenSpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDm", DbType="Int")]
		public System.Nullable<int> MaDm
		{
			get
			{
				return this._MaDm;
			}
			set
			{
				if ((this._MaDm != value))
				{
					if (this._DanhMuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDmChanging(value);
					this.SendPropertyChanging();
					this._MaDm = value;
					this.SendPropertyChanged("MaDm");
					this.OnMaDmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMuc_SanPham", Storage="_DanhMuc", ThisKey="MaDm", OtherKey="MaDm", IsForeignKey=true)]
		public DanhMuc DanhMuc
		{
			get
			{
				return this._DanhMuc.Entity;
			}
			set
			{
				DanhMuc previousValue = this._DanhMuc.Entity;
				if (((previousValue != value) 
							|| (this._DanhMuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhMuc.Entity = null;
						previousValue.SanPhams.Remove(this);
					}
					this._DanhMuc.Entity = value;
					if ((value != null))
					{
						value.SanPhams.Add(this);
						this._MaDm = value.MaDm;
					}
					else
					{
						this._MaDm = default(Nullable<int>);
					}
					this.SendPropertyChanged("DanhMuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class QueryAllSanPhamResult
	{
		
		private int _MaSp;
		
		private string _TenSp;
		
		private System.Nullable<int> _DonGia;
		
		private System.Nullable<int> _MaDm;
		
		public QueryAllSanPhamResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSp", DbType="Int NOT NULL")]
		public int MaSp
		{
			get
			{
				return this._MaSp;
			}
			set
			{
				if ((this._MaSp != value))
				{
					this._MaSp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSp", DbType="NVarChar(250)")]
		public string TenSp
		{
			get
			{
				return this._TenSp;
			}
			set
			{
				if ((this._TenSp != value))
				{
					this._TenSp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDm", DbType="Int")]
		public System.Nullable<int> MaDm
		{
			get
			{
				return this._MaDm;
			}
			set
			{
				if ((this._MaDm != value))
				{
					this._MaDm = value;
				}
			}
		}
	}
	
	public partial class QueryDanhMucResult
	{
		
		private int _MaDm;
		
		private string _TenDm;
		
		public QueryDanhMucResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDm", DbType="Int NOT NULL")]
		public int MaDm
		{
			get
			{
				return this._MaDm;
			}
			set
			{
				if ((this._MaDm != value))
				{
					this._MaDm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDm", DbType="NVarChar(250)")]
		public string TenDm
		{
			get
			{
				return this._TenDm;
			}
			set
			{
				if ((this._TenDm != value))
				{
					this._TenDm = value;
				}
			}
		}
	}
	
	public partial class QueryDanhMucTheoMaDmResult
	{
		
		private int _MaDm;
		
		private string _TenDm;
		
		public QueryDanhMucTheoMaDmResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDm", DbType="Int NOT NULL")]
		public int MaDm
		{
			get
			{
				return this._MaDm;
			}
			set
			{
				if ((this._MaDm != value))
				{
					this._MaDm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDm", DbType="NVarChar(250)")]
		public string TenDm
		{
			get
			{
				return this._TenDm;
			}
			set
			{
				if ((this._TenDm != value))
				{
					this._TenDm = value;
				}
			}
		}
	}
	
	public partial class QuerySanPhamTheoMaDmResult
	{
		
		private int _MaSp;
		
		private string _TenSp;
		
		private System.Nullable<int> _DonGia;
		
		private System.Nullable<int> _MaDm;
		
		public QuerySanPhamTheoMaDmResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSp", DbType="Int NOT NULL")]
		public int MaSp
		{
			get
			{
				return this._MaSp;
			}
			set
			{
				if ((this._MaSp != value))
				{
					this._MaSp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSp", DbType="NVarChar(250)")]
		public string TenSp
		{
			get
			{
				return this._TenSp;
			}
			set
			{
				if ((this._TenSp != value))
				{
					this._TenSp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDm", DbType="Int")]
		public System.Nullable<int> MaDm
		{
			get
			{
				return this._MaDm;
			}
			set
			{
				if ((this._MaDm != value))
				{
					this._MaDm = value;
				}
			}
		}
	}
	
	public partial class QuerySanPhamTheoMaSpResult
	{
		
		private int _MaSp;
		
		private string _TenSp;
		
		private System.Nullable<int> _DonGia;
		
		private System.Nullable<int> _MaDm;
		
		public QuerySanPhamTheoMaSpResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSp", DbType="Int NOT NULL")]
		public int MaSp
		{
			get
			{
				return this._MaSp;
			}
			set
			{
				if ((this._MaSp != value))
				{
					this._MaSp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSp", DbType="NVarChar(250)")]
		public string TenSp
		{
			get
			{
				return this._TenSp;
			}
			set
			{
				if ((this._TenSp != value))
				{
					this._TenSp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDm", DbType="Int")]
		public System.Nullable<int> MaDm
		{
			get
			{
				return this._MaDm;
			}
			set
			{
				if ((this._MaDm != value))
				{
					this._MaDm = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
